spring:
  profiles:
    active: dev

thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true

# logging:
#   level:
#     jdbc: INFO
#     com.thoughtlib.springbatchpractice: INFO
#     org.hibernate.SQL: INFO
#     org.hibernate.type: INFO
#   file:
#     path: /tmp